export enum DateTimePattern {
  SHORT_DATE = 'd',
  FULL_DATE = 'dd',
  SHORT_YEAR = 'yy',
  FULL_YEAR = 'yyyy',
  SHORT_MONTH = 'MM',
  MEDIUM_MONTH = 'MMM',
  FULL_MONTH = 'MMMM',
  SHORT_WEEK = 'EE',
  MEDIUM_WEEK = 'EEE',
  FULL_WEEK = 'EEEE',
  SHORT_HOUR = 'h',
  FULL_HOUR = 'hh',
  SHORT_24_HOUR = 'H',
  FULL_24_HOUR = 'HH',
  SHORT_MINUTE = 'm',
  FULL_MINUTE = 'mm',
  SHORT_SECOND = 's',
  FULL_SECOND = 'ss',
  SHORT_MILLISECOND = 'S',
  MEDIUM_MILLISECOND = 'SS',
  FULL_MILLISECOND = 'SSS',
  AM_PM_MARKER = 'a',
}
